//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        public int Medicine_ID { get; set; }
        public string Medicine_Name { get; set; }
        public string Medicine_Salary { get; set; }
        public Nullable<System.DateTime> Expiry_Date { get; set; }
        public Nullable<System.DateTime> Production_Date { get; set; }
    }
}
